# Generated by Django 2.1.3 on 2018-11-23 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.FileField(default=None, upload_to=''),
        ),
    ]
