# Generated by Django 2.1.3 on 2018-11-23 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0002_auto_20181122_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='picture',
            field=models.FileField(upload_to=''),
        ),
    ]
