# Generated by Django 2.1.3 on 2018-11-12 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0002_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='is_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
