# Generated by Django 2.1.3 on 2018-11-23 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0003_auto_20181122_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
