# Generated by Django 2.1.3 on 2018-11-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0004_auto_20181123_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
