# Generated by Django 2.1.3 on 2018-11-24 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0005_auto_20181123_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
