# Generated by Django 2.1.3 on 2018-11-29 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0008_auto_20181128_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('subject', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('recipient', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='as_recipient', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='as_sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
