# Generated by Django 2.1.3 on 2018-11-29 15:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0010_auto_20181129_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='msg_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mail',
            name='recipient',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='as_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='sender',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='as_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mail',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
