# Generated by Django 2.1.3 on 2018-11-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0011_auto_20181129_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
