# Generated by Django 2.1.3 on 2018-11-29 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positivepets', '0012_auto_20181129_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='subject',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
