"""
color_map: dictionary {html_color_name: {button_text_color=x, display_name=x]
"""

color_map= {
    'antiquewhite': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Antique White'},
    'aqua': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Aqua'},
    'aquamarine': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Aquamarine'},
    'beige': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Beige'},
    'bisque': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Bisque'},
    'black': {'button_text_color': 'lightgray', 'display_name': 'Black'},
    'blue': {'button_text_color': 'lightgray', 'display_name': 'Blue'},
    'blueviolet': {'button_text_color': 'lightgray', 'display_name': 'Blue Violet'},
    'brown': {'button_text_color': 'lightgray', 'display_name': 'Brown'},
    'burlywood': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Burlywood'},
    'cadetblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Cadet Blue'},
    'chartreuse': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Chartreuse'},
    'chocolate': {'button_text_color': 'lightgray', 'display_name': 'Chocolate'},
    'coral': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Coral'},
    'cornflowerblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Cornflower Blue'},
    'crimson': {'button_text_color': 'lightgray', 'display_name': 'Crimson'},
    'cyan': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Cyan'},
    'darkblue': {'button_text_color': 'lightgray', 'display_name': 'Dark Blue'},
    'darkcyan': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Dark Cyan'},
    'darkgoldenrod': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Dark Goldenrod'},
    'darkgreen': {'button_text_color': 'lightgray', 'display_name': 'Dark Green'},
    'darkkhaki': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Dark Khaki'},
    'darkmagenta': {'button_text_color': 'lightgray', 'display_name': 'Dark Magenta'},
    'darkolivegreen': {'button_text_color': 'lightgray', 'display_name': 'Dark Olive Green'},
    'darkorange': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Dark Orange'},
    'darkorchid': {'button_text_color': 'lightgray', 'display_name': 'Dark Orchid'},
    'darkred': {'button_text_color': 'lightgray', 'display_name': 'Dark Red'},
    'darksalmon': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Dark Salmon'},
    'darkseagreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Dark Sea Green'},
    'darkslateblue': {'button_text_color': 'lightgray', 'display_name': 'Dark Slate Blue'},
    'darkslategray': {'button_text_color': 'lightgray', 'display_name': 'Dark Slate Gray'},
    'darkturquoise': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Dark Turquoise'},
    'darkviolet': {'button_text_color': 'lightgray', 'display_name': 'Dark Violet'},
    'deeppink': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Deep Pink'},
    'deepskyblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Deep Sky Blue'},
    'dimgray': {'button_text_color': 'lightgray', 'display_name': 'Dim Gray'},
    'dodgerblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Dodger Blue'},
    'firebrick': {'button_text_color': 'lightgray', 'display_name': 'Fire Brick'},
    'forestgreen': {'button_text_color': 'lightgray', 'display_name': 'Forest Green'},
    'fuchsia': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Fuchsia'},
    'gainsboro': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Gainsboro'},
    'gold': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Gold'},
    'goldenrod': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Goldenrod'},
    'gray': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Gray'},
    'green': {'button_text_color': 'lightgray', 'display_name': 'Green'},
    'greenyellow': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Green Yellow'},
    'hotpink': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Hot Pink'},
    'indianred': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Indian Red'},
    'indigo': {'button_text_color': 'lightgray', 'display_name': 'Indigo'},
    'khaki': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Khaki'},
    'lavender': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Lavender'},
    'lawngreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Lawn Green'},
    'lightblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Blue'},
    'lightcoral': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Coral'},
    'lightgray': {'button_text_color': 'rgb(20,20,20)', 'display_name': 'Light Gray'},
    'lightgreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Green'},
    'lightpink': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Pink'},
    'lightsalmon': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Salmon'},
    'lightseagreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Sea Green'},
    'lightskyblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Sky Blue'},
    'lightslategray': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Slate Gray'},
    'lightsteelblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Light Steel Blue'},
    'lime': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Lime'},
    'limegreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Lime Green'},
    'magenta': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Magenta'},
    'maroon': {'button_text_color': 'lightgray', 'display_name': 'Maroon'},
    'mediumaquamarine': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Medium Aquamarine'},
    'mediumblue': {'button_text_color': 'lightgray', 'display_name': 'Medium Blue'},
    'mediumorchid': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Medium Orchid'},
    'mediumpurple': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Medium Purple'},
    'mediumseagreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Medium Sea Green'},
    'mediumslateblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Medium Slate Blue'},
    'mediumspringgreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Medium Spring Green'},
    'mediumturquoise': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Medium Turquoise'},
    'mediumvioletred': {'button_text_color': 'lightgray', 'display_name': 'Medium Violet Red'},
    'midnightblue': {'button_text_color': 'lightgray', 'display_name': 'Midnight Blue'},
    'mistyrose': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Misty Rose'},
    'moccasin': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Moccasin'},
    'navajowhite': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Navajo White'},
    'navy': {'button_text_color': 'lightgray', 'display_name': 'Navy'},
    'olive': {'button_text_color': 'lightgray', 'display_name': 'Olive'},
    'olivedrab': {'button_text_color': 'lightgray', 'display_name': 'Olive Drab'},
    'orange': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Orange'},
    'orangered': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Orange Red'},
    'orchid': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Orchid'},
    'palegoldenrod': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Pale Goldenrod'},
    'palegreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Pale Green'},
    'paleturquoise': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Pale Turquoise'},
    'palevioletred': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Pale Violet Red'},
    'papayawhip': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Papaya Whip'},
    'peachpuff': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Peach Puff'},
    'peru': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Peru'},
    'pink': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Pink'},
    'plum': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Plum'},
    'powderblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Powder Blue'},
    'purple': {'button_text_color': 'lightgray', 'display_name': 'Purple'},
    'rebeccapurple': {'button_text_color': 'lightgray', 'display_name': 'Rebecca Purple'},
    'red': {'button_text_color': 'lightgray', 'display_name': 'Red'},
    'rosybrown': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Rosy Brown'},
    'royalblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Royal Blue'},
    'saddlebrown': {'button_text_color': 'lightgray', 'display_name': 'Saddle Brown'},
    'salmon': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Salmon'},
    'sandybrown': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Sandy Brown'},
    'seagreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Sea Green'},
    'sienna': {'button_text_color': 'lightgray', 'display_name': 'Sienna'},
    'silver': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Silver'},
    'skyblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Sky Blue'},
    'slateblue': {'button_text_color': 'lightgray', 'display_name': 'Slate Blue'},
    'slategray': {'button_text_color': 'lightgray', 'display_name': 'Slate Gray'},
    'springgreen': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Spring Green'},
    'steelblue': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Steel Blue'},
    'tan': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Tan'},
    'teal': {'button_text_color': 'lightgray', 'display_name': 'Teal'},
    'thistle': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Thistle'},
    'tomato': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Tomato'},
    'turquoise': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Turquoise'},
    'violet': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Violet'},
    'wheat': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Wheat'},
    'yellow': {'button_text_color': 'rgb(40,40,40)', 'display_name': 'Yellow'}
}